### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#148]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app. All happens offline (no internet needed).

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, HBAR, DASH, FTM, XRP, XDC, ADA, XLM, KAS, XMR, SEI, INJ, SUI addresses available for donations (addresses have to be copyable).

I don't want going around to websites. I don't want support FIAT economy.
I don't want leave the app environment in order to make a donation.

Of course, once the crypto address is copied, the donation process will continue on the user's non-custodial wallet.

Here an integration example made by other developers.

![1000092943](https://github.com/AdamGuidarini/MediTrak/assets/113377431/528e3065-97e2-4851-a590-ecaece5e2727)

**Comment by jocmp** [comment]
Hey there, I appreciate the thought! That said I'm only accepting donations through ko-fi right now. This protects me from fraud and protects the you, the payer, too since ko-fi has a Trust and Safety team to marshal payments. Maybe if this project picks up steam I'll consider adding a button in-app too.
