### ISSUE TITLE
Add next/previous buttons for paging through articles

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#265]
Reference

- https://github.com/jocmp/capyreader/discussions/241

**Comment by Philippe-Choquette** [comment]
When the update with the bottom bar was pushed, I first found it a bit odd to have so much vertical space used for just one button, especially since gesture navigation between articles was added as well. I disabled the "Pin toolbars" option to get some of that space back.

I wanted to suggest the following, if it makes sense:
- Adding a "previous article" button to the bottom bar, as for users who disable gesture navigation, they only have a "next article" button available currently.
- A possibility to disable the bottom bar, or let the user pick between "buttons" and gestures to navigate between articles.

Thank you @jocmp as always for keeping us with our suggestions!

**Comment by jocmp** [comment]
hey @Philippe-Choquette - I need to think about how best to surface these options (too many options can cause overload). I like the idea of disabling the bottom bar - I agree it takes up a lot of vertical space. I'll track bottom bar config here https://github.com/jocmp/capyreader/issues/397. Stay tuned!
