### ISSUE TITLE
No media load for Some websites

### ISSUE THREAD

**Issue by tawalan777** [jocmp/capyreader#302]
### Steps to Reproduce

When opening a news from some websites it's not loading the media 

### Expected behavior

Can't load the photos of the news feom Some websites

### Screenshots or screen recording

![Screenshot_20240824_034632_Capy Reader](https://github.com/user-attachments/assets/e46b3163-ac20-4a75-8160-e7bad67709c8)

**Comment by jocmp** [comment]
hey @tawalan777 - Can you confirm that you're looking at this feed? https://www.aljazeera.com/xml/rss/all.xml

If that's the case, images don't load in the non full-content mode because Al Jazeera doesn't include them in the feed summary. Images should load in full content mode though sometimes the lead image still doesn't load based on the article's markup.

**Comment by tawalan777** [comment]
Hellp dear,

Yea it was that one as a sample, I like your app simplicity and it's doing
the work, I'm shifting from feedly nad Google News.

Thanks and Regards

**Comment by jocmp** [comment]
Closing for now. If you have more examples please post them to the discussion https://github.com/jocmp/capyreader/discussions/322
