### ISSUE TITLE
Load full content not parsing full article on some sites

### ISSUE THREAD

**Issue by chrisbd** [jocmp/capyreader#305]
### Steps to Reproduce

I've found some websites when clicking load full content isn't returning the full article. In my case this is happening on BBC sport articles 

### Expected behavior

Full article is available to read when clicking load 

### Device, Operating system, and app version

Pixel 8 Pro - Android 14

**Comment by jocmp** [comment]
@chrisbd can you share the RSS link to the feed?

**Comment by chrisbd** [comment]
The feed is: http://feeds.bbci.co.uk/sport/rss.xml?edition=uk

This is an example article that doesn't seem to load the full text: https://www.bbc.com/sport/football/articles/c703j22z4z8o

**Comment by jocmp** [comment]
Thanks for this. One more thing - what version of the app are you running? This can be found in settings.

**Comment by chrisbd** [comment]
@jocmp no problem. App version is 2024.08.1031

**Comment by jocmp** [comment]
Got it. I recently updated the parsing library I used for full content. So this feed should be fixed in the next releases for GPlay and F-Droid. Here's what the latest version looks like compared to 2024.08.1031.

<table>
<tr>
<th>2024.08.1031</th>
<th>2024.08.1036-dev</th>
</th>
<tr>
<td valign="top">
<img src="https://github.com/user-attachments/assets/0e669af7-cae9-47cf-97c9-79a842eff37d" width="500px">
</td>
<td  valign="top">
<img src="https://github.com/user-attachments/assets/07b7db1d-d6dd-4b98-a8b9-86dcd2981df2" width="500px">
</td>
</table>

**Comment by jocmp** [comment]
Fix with the updated parser is live in 2024.08.1036-dev and above.
