### ISSUE TITLE
Navigation from article to article

### ISSUE THREAD

**Issue by montechristos** [jocmp/capyreader#369]
Thanks for the tool, it is very promising

Feature request:
It would be great to be able to navigate from article to article (back and forth) from within the article.
In other RSS tools, swipe left-right does this.

Thanks in advance

**Comment by jocmp** [comment]
hey @montechristos. thanks for trying out the app. I'm currently wrapping up a first iteration of this with #265 with buttons. I'm not including a gesture yet due to some complications in how the app is built.

Are there any RSS tools that you're thinking of specifically that do left-right nav well?

**Comment by montechristos** [comment]
Thanks for reaching back.
I have been using Flym news reader for many years now. Unfortunately it is out of support, so I am looking for alternatives.
Capy is the top candidate for replacing my beloved Flym.

So, the navigation of Flym is great. Please have a look.
Some other features that I find great:
- left-right navigation between articles
- you can completely 'hide' the read articles (so they are not in the way in the lists)
- fixed height lists, that make the list look very clean
- ...

PS: my main reading device is a e-ink android tablet. Let me know if you would like feedback on using capy on it.

**Comment by jocmp** [comment]
Cool, I'll take another look at Flym. I remember trying it out years ago when it was still supported.

If you have any feedback about e-ink tablets, definitely open a discussion (https://github.com/jocmp/capyreader/discussions) so that others can chime in. I'm interested in this use case since I have a Boox e-reader. I can't promise I'll get to every feature request but I'll do my best as time permits and when they make sense to add.

**Comment by sozifa** [comment]
Flym is definitely worth a look to get some inspiration - has been my default rss reader till I discovered capy ;-) - as it has been abandoned for years now the ui feels a bit outdated and capy looks more modern and simplified - but still the gestures used in capy for navigation, loading full article,... are still worth another look ;-)

**Comment by jocmp** [comment]
A small update. I'm very close to adding swipe navigation. I'm working on adding the options to settings now. Here's a demo of how it works.

## Default, swipe between articles

This is similar functionality to Reeder and ReadYou but is built from the ground up using code from Google (#375).

https://github.com/user-attachments/assets/948d30c1-87ed-4678-ad88-5e76ee656f96

## Option, swipe down to load full content

@sozifa let me know if this is what you've envisioned

https://github.com/user-attachments/assets/0b11c569-c86c-4977-b501-b330f4204efa

**Comment by sozifa** [comment]
That's absolutely perfect- many thanks :-)

**Comment by jocmp** [comment]
This change is live in [2024.09.1050-dev](https://github.com/jocmp/capyreader/releases/tag/2024.09.1050-dev). I'll include it in the next Google Play release in a few days too.

**Comment by sozifa** [comment]
You're legend - very much appreciated

**Comment by jocmp** [comment]
This is live in the Google Play Store now too with version 2024.09.1052. Closing for now.
