### ISSUE TITLE
Better YouTube handling

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#465]
- [ ] Handle iframes like Feedbin (prevent swipe events)

**Comment by scharmach** [comment]
Maybe this is better suited here instead of opening a new issue. Let me know what _you_ think, @jocmp.

If you scroll through an article, then YouTube videos get already played (or paused) while you scroll over them. Here's an example with a random article:

https://github.com/user-attachments/assets/48bdd603-3904-44f9-a9e0-12399a669a7c

This can be quite irritating and in my opinion the playback should be harder to trigger, with a tap instead of on scrolling.

Also, thanks a lot for this great app! 🙏

**Comment by jocmp** [comment]
Hey @scharmach thanks for reporting. I was able to reproduce this. It looks like any touch event (including a swipe) will autoplay YouTube. It's possible to avoid if you swipe around the video, but it's not easy. I'll see if I can modify this so that it's not so easy to start the video.

**Comment by jocmp** [comment]
I'm working on a custom overlay that should prevent YouTube's touchy behavior. On click the video will start as expected. Here's a sneak peek!

https://github.com/user-attachments/assets/a388f8f6-30f9-4bba-98ac-4c111346827c

**Comment by jocmp** [comment]
This is available as of [2024.12.1085-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1085-dev).
