### ISSUE TITLE
[Feat]: Simplified hamburger menu

### ISSUE THREAD

**Issue by tvnmguy** [jocmp/capyreader#529]
•Before:

![Screenshot_2024-11-20-10-04-22-834_com.capyreader.app.jpg](https://github.com/user-attachments/assets/1a9fc974-ccb4-432e-a90c-b4e15e2ac4f6)

![Screenshot_2024-11-20-10-04-28-191_com.capyreader.app.jpg](https://github.com/user-attachments/assets/5f7ac1a9-c885-4045-8de3-496900d5865a)

•After:

![img_2024_11_20_10_04_08.jpg](https://github.com/user-attachments/assets/c545d277-6178-462b-9c09-bbc85c617afc)

**Comment by jocmp** [comment]
Thanks for the suggestion @tvnmguy. I want to keep filters the same for now for two main reasons.

One reason is that it provides some hierarchy in that a filter acts on a different level than a feed or folder. The other reason is that it would be a big code change since filters will also change which feeds and folders appear based on whether you click "Starred" or "All" for example.
